# SPDX-License-Identifier: AGPL-3.0-or-later
services:
  tokai:
    build:
      context: .
    ports:
      - "127.0.0.1:${TOKAI_PORT-8000}:${TOKAI_PORT-8000}"
    restart: unless-stopped
    environment:
      TOKAI_HOST: ${TOKAI_HOST-0.0.0.0}
      TOKAI_PORT: ${TOKAI_PORT-8000}
      TOKAI_LOG_LEVEL: ${TOKAI_LOG_LEVEL-info}
